<?php
/**
 * Generated by Haxe 4.0.1
 */

namespace helder\std\haxe\_Unserializer;

use \helder\std\php\Boot;

class NullResolver {
	/**
	 * @var NullResolver
	 */
	static public $instance;

	/**
	 * @return NullResolver
	 */
	static public function get_instance () {
		#/home/runner/haxe/versions/4.0.1/std/haxe/Unserializer.hx:492: lines 492-493
		if (NullResolver::$instance === null) {
			#/home/runner/haxe/versions/4.0.1/std/haxe/Unserializer.hx:493: characters 4-33
			NullResolver::$instance = new NullResolver();
		}
		#/home/runner/haxe/versions/4.0.1/std/haxe/Unserializer.hx:494: characters 3-18
		return NullResolver::$instance;
	}

	/**
	 * @return void
	 */
	public function __construct () {
	}

	/**
	 * @param string $name
	 * 
	 * @return Class
	 */
	public function resolveClass ($name) {
		#/home/runner/haxe/versions/4.0.1/std/haxe/Unserializer.hx:484: characters 3-14
		return null;
	}

	/**
	 * @param string $name
	 * 
	 * @return Enum
	 */
	public function resolveEnum ($name) {
		#/home/runner/haxe/versions/4.0.1/std/haxe/Unserializer.hx:487: characters 3-14
		return null;
	}
}

Boot::registerClass(NullResolver::class, 'haxe._Unserializer.NullResolver');
Boot::registerGetters('helder\\std\\haxe\\_Unserializer\\NullResolver', [
	'instance' => true
]);
