<?php
/**
 * Generated by Haxe 4.0.0+ef18b627e
 */

namespace helder\std\haxe\xml\_Access;

use \helder\std\php\Boot;
use \helder\std\Xml;
use \helder\std\php\_Boot\HxException;

final class HasAttribAccess_Impl_ {
	/**
	 * @param Xml $this
	 * @param string $name
	 * 
	 * @return bool
	 */
	static public function resolve ($this1, $name) {
		#/home/runner/haxe/versions/4.0.0/std/haxe/xml/Access.hx:60: lines 60-61
		if ($this1->nodeType === Xml::$Document) {
			#/home/runner/haxe/versions/4.0.0/std/haxe/xml/Access.hx:61: characters 4-9
			throw new HxException("Cannot access document attribute " . ($name??'null'));
		}
		#/home/runner/haxe/versions/4.0.0/std/haxe/xml/Access.hx:62: characters 3-27
		return $this1->exists($name);
	}
}

Boot::registerClass(HasAttribAccess_Impl_::class, 'haxe.xml._Access.HasAttribAccess_Impl_');
