<?php
/**
 * Generated by Haxe 4.0.0+ef18b627e
 */

namespace helder\std\haxe\_EntryPoint;

use \helder\std\php\Boot;

class Thread {
	/**
	 * @param \Closure $f
	 * 
	 * @return void
	 */
	static public function create ($f) {
		#/home/runner/haxe/versions/4.0.0/std/haxe/EntryPoint.hx:26: characters 3-6
		$f();
	}
}

Boot::registerClass(Thread::class, 'haxe._EntryPoint.Thread');
