name: php

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Haxe version'
        required: true
        default: '4.1.4'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
      - run: yarn
      - run: yarn lix install haxe ${{ github.event.inputs.version }}
      
      - uses: oleksiyrudenko/gha-git-credentials@v1

      - run: yarn build:php
      - run: yarn publish:php
      - run: yarn version:php
      